name: Feature request
description: Suggest an idea for JSONBlade or the Monaco plugin
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: Describe the use case or pain point
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions you've considered
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, prior art, examples
    validations:
      required: false
