export const FILTERS = [
  "upper",
  "lower",
  "capitalize",
  "trim",
  "default",
  "slug",
  "join",
  "length",
  "first",
  "last",
  "map",
  "filter",
  "reverse",
  "sort",
  "unique",
  "equals",
  "not",
  "bool",
  "gt",
  "gte",
  "lt",
  "lte",
  "contains",
  "startsWith",
  "endsWith",
  "isEmpty",
  "round",
  "ceil",
  "floor",
  "abs",
  "currency",
  "percentage",
  "multiply",
  "divide",
  "add",
  "subtract",
  "formatDate",
  "fromNow",
  "isoDate",
  "dayOfWeek",
  "timestamp",
  "isEmail",
  "isURL",
  "isUUID",
  "isNumber",
  "isInteger",
  "isPhoneNumber",
  "minLength",
  "maxLength",
  "matches",
  "base64Encode",
  "base64Decode",
  "escape",
  "unescape",
  "urlEncode",
  "urlDecode",
  "json",
  "keys",
  "values",
  "entries",
];

export const DIRECTIVES = ["if", "unless", "each", "set", "else"];

export const LOOP_KEYWORDS = ["@index", "@first", "@last"];

export const LANGUAGE_ID = "jsonblade";

export const THEME_NAME = "jsonblade-theme";

export const MAX_ANALYSIS_DEPTH = 4;
